[workspace]
members = ["mutli-ai-chat-app/src-tauri"]
resolver = "2"

[workspace.dependencies]
reqwest = {version ="0.12.24",features = ["json","stream"]}
tokio = {version = "1.48.0",features = ["full","rt-multi-thread"]}
anyhow = "1.0.100"
futures = "0.3"